### ISSUE TITLE
Move to julia-actions org

### ISSUE THREAD

**Issue by IanButterworth** [cjdoris/julia-downgrade-compat-action#1]
There seems to be general interest in what this does so it seems a good fit for https://github.com/julia-actions

**Comment by cjdoris** [comment]
That suits me - I can initiate the transfer now if you like?

**Comment by IanButterworth** [comment]
Sounds good. Perhaps rename the repo to `julia-downgrade-compat` first, as is standard for the names of actions in that org?

**Comment by cjdoris** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

> Note: GitHub will not redirect calls to an action hosted by a renamed repository. Any workflow that uses that action will fail with the error repository not found. Instead, create a new repository and action with the new name and archive the old repository.

So the advice is to never rename an action repo. I think the solution is to fork the repo to the julia-actions org (with the correct name) and archive the old repo.

Do you want to make the fork, or add me to the julia-actions org and I can do it?

**Comment by IanButterworth** [comment]
Renamed fork made here https://github.com/julia-actions/julia-downgrade-compat

I notice that the tags don't copy over automatically..

**Comment by IanButterworth** [comment]
@cjdoris I've:
- updated the fork readme for org and name
- tagged v1 & v1.0 @ v1.0.7 commit (v1 is still on v1.0.6 on this repo currently)
- pushed the tags to the fork
- made a release https://github.com/julia-actions/julia-downgrade-compat/releases/tag/v1.0.7

If all that looks good to you, I'll let you decide how to publish the move.

I do note that there aren't any tests yet, so CI would be good, but not a blocker IMO

**Comment by cjdoris** [comment]
Great thanks! Agreed some some basic tests would be good.

**Comment by cjdoris** [comment]
Leaving this ticket open until I deprecate the old action.

**Comment by cjdoris** [comment]
Deprecated. Archiving this repo now.
